import Link from "next/link";
import { Shell, services } from "../components";

const details: Record<string,{eyebrow:string; title:string; intro:string; items?:string[]; investment?:string; timeline?:string}> = {
  "services": { eyebrow:"How we help", title:"Bring every piece together.", intro:"Mosaic is a connected journey—from a clearer direction to the systems that make it real." },
  "services/vision": { eyebrow:"01 / Vision", title:"Rediscover where you’re going.", intro:"Before we make anything, we make space to see what matters.", items:["Vision workshop","Business and brand audit","Customer journey","Messaging direction","Systems audit","Prioritized roadmap"], investment:"Starting at $2,500", timeline:"1–2 weeks" },
  "services/experience": { eyebrow:"02 / Experience", title:"Bring your vision to life.", intro:"A considered digital home that makes it easier for the right people to understand, trust, and choose you.", items:["Website strategy","UX and information architecture","Custom design and development","Copy direction","CRM connection","SEO foundation"], investment:"Starting at $4,500", timeline:"4–8 weeks" },
  "services/connect": { eyebrow:"03 / Connect", title:"Make your business work beautifully.", intro:"We create manageable systems and workflows that give your team room to do their best work.", items:["Internal processes","CRM structure","Workflow automation","AI-assisted workflows","Dashboards and reporting","SOPs and training"], investment:"Starting at $5,000", timeline:"4–10 weeks" },
  "services/grow": { eyebrow:"04 / Grow", title:"Keep moving forward.", intro:"A long-term strategic partner for the details that keep a good business moving in the right direction.", items:["Monthly strategy","Website updates","Automation maintenance","Reporting review","New improvements","Team consulting"], investment:"From $750/month", timeline:"Ongoing" },
  "process": { eyebrow:"The Mosaic Method", title:"A clear path forward.", intro:"Every engagement should leave the business clearer than we found it.", items:["Discover — understand before recommending technology.","Clarify — remove unnecessary complexity.","Create — bring the customer-facing vision to life.","Connect — build the systems behind it.","Empower — document, train, and leave you capable." ] },
  "about": { eyebrow:"About Mosaic", title:"Clarity creates momentum.", intro:"Mosaic is a business systems studio for founders who are ready for the pieces of their business to work together." },
  "work": { eyebrow:"Selected work", title:"Thoughtful work, built to last.", intro:"A few examples of the clearer, more connected businesses we help create." },
  "playbook": { eyebrow:"The Mosaic Playbook", title:"Every business begins with a vision.", intro:"Not a website. Not software. Not a process. A vision." },
  "start": { eyebrow:"Start with vision", title:"Let’s make your next chapter clear.", intro:"Tell us a little about what is working, what is not, and where you want to go." },
  "portal": { eyebrow:"Client portal", title:"A place for the work in progress.", intro:"The Mosaic client portal is coming soon. Existing clients can reach Lauren directly in the meantime." },
  "privacy": { eyebrow:"Privacy", title:"Privacy policy.", intro:"A plain-language privacy policy will be published here before Mosaic begins collecting customer data." },
  "terms": { eyebrow:"Terms", title:"Terms of use.", intro:"Terms of use will be published here before Mosaic begins accepting client engagements online." },
};
export default async function CatchAll({ params }: {params: Promise<{slug:string[]}>}) { const {slug}=await params; const key=slug.join("/"); const item=details[key] || {eyebrow:"Case study", title:slug.at(-1)?.replaceAll("-", " ") || "Not found", intro:"A closer look at a business made clearer through thoughtful strategy, design, and systems."}; const isServices=key==="services"; const isPlaybook=key==="playbook"; return <Shell><section className="page-hero"><p className="kicker">{item.eyebrow}</p><h1>{item.title}</h1><p className="lede">{item.intro}</p>{key==="start"&&<form className="contact-form" action="/api/contact" method="post"><label>Email address<input required type="email" name="email" placeholder="you@company.com"/></label><button className="button">Start the conversation ↗</button></form>}</section>{isServices?<section className="service-index">{services.map(([n,title,copy,href])=><Link href={href} className="service-row" key={title}><span>{n}</span><h3>{title}</h3><p>{copy}</p><b>↗</b></Link>)}</section>:isPlaybook?<section className="manifesto-copy"><p>Every business begins with a vision.</p><p>As businesses grow, that vision often becomes harder to see. New tools are added. Processes become disconnected. Workarounds replace intention.</p><p>We believe simplicity is power. We believe technology should feel manageable. We believe businesses work best when every piece has a purpose.</p><p>Our role isn’t to add more. Our role is to reveal what matters—to replace confusion with clarity, and reconnect every piece to the vision that started it all.</p><p><em>That’s why Mosaic exists.</em></p></section>:<section className="detail-section">{item.items&&<ul>{item.items.map(x=><li key={x}>{x}</li>)}</ul>}{item.investment&&<div className="investment"><span>Investment</span><strong>{item.investment}</strong><span>Typical timeline</span><strong>{item.timeline}</strong></div>}<Link className="button" href="/start">Start With Vision <b>↗</b></Link></section>}</Shell>; }
